### ISSUE TITLE
Crash in module browser in EO-102

### ISSUE THREAD

**Issue by david-c14** [david-c14/SubmarineFree#108]
Found by @persywho

**Comment by david-c14** [comment]
https://github.com/VCVRack/Rack/issues/1748

**Comment by david-c14** [comment]
Version 1.1.5 of vcvrack is not the latest. I can't see why it would make a difference, but the plugins are built for v1.1.6.

How long ago did rack still work for you? I mean, did you use it successfully last week, or have you been away from it for a while?  I've released 3 versions in the last two weeks, so it might help me to know when the problem started.

**Comment by persywho** [comment]
hi,
yes rack was working fine. i just updated my plugins yesterday and it
started to crash. i hadnt updated things this week so i may have missed
some of your latest updates.

i will switch to 1.1.6 and see of that helps.

Persy

**Comment by persywho** [comment]
guess it was time for me to update to 1.1.6 which actually doesnt update
correctly on osx. it created a separate 1.1.6 zip file rather than
replacing 1.1.5. but now ra k is not crashing. i looked at the 1.1.6 change
log and it was minimal so i didnt think that was the issue but guess i was
wrong.

persy

**Comment by david-c14** [comment]
I'm glad it works. Its very difficult for me to work with bugs on osx, because I don't have access to a mac. 
I couldn't see anything suspicious in the rack changelog either.
