### ISSUE TITLE
Lights Off compatibility ? [feature request]

### ISSUE THREAD

**Issue by davephillips** [david-c14/SubmarineFree#156]
Greetings !

Your TD-202 label panel is sweet, but is there any chance you could make it compatible with Modular Fungi's Lights Off module ? I use the Impromptu Modular's Tact controllers a lot and label their functions with the 202. Alas, the label text disappears in Lights Off mode. It would be very helpful to see those labels in that mode.

Best regards,

Dave Phillips

**Comment by david-c14** [comment]
I tried to make a start on this, but of all the TD-xxx devices, the TD-202 is likely to be the hardest, because of the way it has to rotate the whole viewpoint of the UI.   It's not just drawing the text at 90 degrees, if that's all it was it would be easy.  But it has to rotate the mouse input so that you can select the text.  Lights Off currently bypasses that rotation process.

[LightsOff issue #35](https://github.com/david-c14/ModularFungi/issues/35)

**Comment by david-c14** [comment]
I'll continue to work on it, but it won't be an immediate fix.

**Comment by davephillips** [comment]
Thanks for the response, David, I appreciate your comments. No worries, it's obviously not exactly a productivity enhancement, but if you do find the time for it it'd be pretty neat (I think). Anyway, many thanks for your excellent modules ! :)

**Comment by david-c14** [comment]
This was completed for many devices. But not all.

It has now been completely rewritten for VCVRack v2
