### ISSUE TITLE
AG-106 AND Gates 

### ISSUE THREAD

**Issue by matthleg** [david-c14/SubmarineFree#47]

**Comment by david-c14** [comment]
What exactly would it do?  And is your use-case not covered by the FF-xxx devices?

**Comment by matthleg** [comment]
I have A and B trigger and I want one gate output.
It is to use midi contrôler with combination of button (combination of 2
buttons to run something [and buttons serve for different things so it can
only be set momentary]) . I could use the AGmodule + the ff but it's a big
patch and I need this combination 20 times so I am trying to reduce number
of modules...

**Comment by david-c14** [comment]
Have I understood correctly:
So you want 20 independent flip-flops, each with 2 (or more) inputs.  When both (all) inputs are high, the gate switches state

I can see why you would want to keep the number of modules down. 

I'll have to think about it, because it feels like quite a big overhead to add to what are supposed to be simply gates.

**Comment by matthleg** [comment]
You understood well, and I also understand it is not so easy to realise...
But thanks for the response and thanks to think about it.

**Comment by david-c14** [comment]
This is not going to happen. But you might get some mileage out of the new DO-105.

**Comment by david-c14** [comment]
Or in a future version I will have polyphonic logic gates
