### ISSUE TITLE
WM-101 'Color one wire' feature doesn't track changes to color list

### ISSUE THREAD

**Issue by jimallman** [david-c14/SubmarineFree#78]
Great module! One thing I notice is that, if you make changes (add/move/delete) to the list of wire colors, the **Color one wire** feature gets confused. Right-clicking a color works as expected, but _double-clicking_ a color shows the color that was in the n-th slot when the patch was loaded!

Saving and re-loading the patch clears this up, but it's apparent that the double-click action isn't tracking changes. Hopefully an easy fix!

**Comment by jimallman** [comment]
It looks like the problem might be a [static color reference](https://github.com/david-c14/SubmarineFree/blob/45667a9ac9ec5a14d1256fb5db28bbc79ec20c62/src/WM1.cpp#L1013) when the initial button loads? Perhaps this
```cpp
		wb->doubleClickHandler = [=]() {
			this->selectWirePanel(color);
		};
```
... could be changed to
```cpp
		wb->doubleClickHandler = [=]() {
			this->selectWirePanel(wb->color);
		};
```

**Comment by david-c14** [comment]
Thanks for spotting this, and particularly for tracking down the cause.

I've found that using anonymous functions for my event model has greatly improved my ability to manage the complexity.  But it does sometimes make it difficult to reason about exactly what is being captured. 

Perhaps I would be better using explicit capture lists instead of [=].

The next release should be in a week or two, so this fix should be included

**Comment by jimallman** [comment]
Awesome! Thanks for your work on these modules -- inspiring stuff.
